import { Roboto, Geist_Mono } from "next/font/google";
import "./globals.css";
import theme from './lib/theme'
import Navbar from "./components/layout/Navbar";
import Footer from './components/layout/footer/Footer'
import ThemeRegistry from "./components/ThemeRegistry";
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],

});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} `}>
        <ThemeRegistry>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}
